### ISSUE TITLE
Precondition failed: host name should have suffix .local

### ISSUE THREAD

**Issue by pixelspark** [Bouke/NetService#10]
Hi Bouke, fellow Dutchie here. Came across your library and integrated it into my project to support Bonjour discovery on Linux. Fine piece of work!

While it works on OSX (well, with some glitches where the local mDNSResponder gets confused doesn't seem to be hearing the advertisements by NetService.. meanwhile I am seeing traffic with the `dns-sd` utility so I think your library works fine) and compiles on Linux, I get the following error:

````
precondition failed: host name 43ff16893f97. should have suffix .local: file /root/.build/checkouts/NetService.git--4183857386241951162/Sources/NetService/Responder.swift, line 6
````

This is where the error is thrown:

````
let hostname = try gethostname() + "."
        precondition(hostname.hasSuffix(".local."), "host name \(hostname) should have suffix .local")
        self.hostname = hostname
````

The cause being that gethostname() returns a host without any domain. Now this happens inside a Docker container (which doesn't appear to have a domain name associated). If this is not fixable, perhaps you should throw an exception here instead (as the error is really dependent on runtime configuration).

**Comment by Bouke** [comment]
Hi Tommy. As reported by the error, the machine's hostname should have the `.local` suffix. Depending on the OS you can use something like `hostnamectl` to change the hostname. This is not an issue with the library, as mDNS host discovery is coupled with the machine's hostname. 

It might be nicer to throw an error somewhere, however it's not possible from `Responder`, as that class is privately instantiated.

**Comment by Bouke** [comment]
As a side-note, the goal of this package is to have a similar API to Cocoa's counterpart. There are some differences in API, and also large gap in functionality. Ideally you'd conditionally use either Cocoa's or this package's NetService in your code:

```swift
#if os(macOS)
import class Cocoa.NetService
#elseif os(Linux)
import class NetService.NetService
#endif
```
