### ISSUE TITLE
Only use `precondition` for incorrect API usage, not for invalid hostname

### ISSUE THREAD

**Issue by Bouke** [Bouke/NetService#11]
Using `precondition` should not be used for user errors, only for incorrect API usage. So we should probably report this error using the delegate's `didNotPublish(error:...)`.

https://github.com/Bouke/NetService/blob/d793820658e7048185c0094fb0f4e5673212e839/Sources/NetService/Responder.swift#L62

**Comment by robreuss** [comment]
Shouldn't the error message read "local." rather than ".local", or do I have those scrambled in my code?

**Comment by Bouke** [comment]
I think so, yes.

The library no longer handles the network side of things, that is outsourced to the dns_sd library provider. We no longer check the hostname.
