### ISSUE TITLE
Server publishes with multiple ip's

### ISSUE THREAD

**Issue by SwatGuard** [Bouke/NetService#13]
I post the service like this: 
```
var serverDelegate: NetServiceDelegate?

  DispatchQueue.global(qos: .background).async {
            let service = NetService(domain: "local.", type: "_remote._tcp.", name: "MacRemote", port: 0)
            service.publish(options: [.listenForConnections])
                    service.schedule(in: .main, forMode: .defaultRunLoopMode)
            service.delegate = self.serverDelegate

            withExtendedLifetime((service, self.serverDelegate)) {
                RunLoop.main.run()

            }

        }
```
Browsing with Bonjour Browser mac app displays two services under "MacRemote"- one with my Mac's ip and another with an APIPA adress (169.254....). Is this normal ?
This is causing my client to find the APIPA ip instead of the normal IP.

Any advice is much appreciated.

**Comment by Bouke** [comment]
Yes this should maybe not be happening. There's some code in place that should filter out such internal IP addresses. However the 169.254. is a self-assigned address, specifically designed to work in situations where no DHCP server is available. I'm not sure how this is handled by other mDNS responders, maybe they broadcast different IPs on different interfaces?

I'm currently rewriting this package on top of dns_sd, which is implemented by Avahi on Linux. It will replace my own implementation of the mDNS responder in this package. You can test it out in the [dns_sd](https://github.com/Bouke/NetService/tree/dns_sd) branch.

**Comment by Bouke** [comment]
The library no longer handles the network side of things, that is outsourced to the dns_sd library provider.
