### ISSUE TITLE
RunLoop on armv7: Illegal instruction

### ISSUE THREAD

**Issue by Bouke** [Bouke/NetService#14]
It seems that RunLoop is not working on the armv7 build. Investigate other solutions.

**Comment by robreuss** [comment]
This build of Swift 4.1.3 from @uraimo should solve the issue:
https://www.dropbox.com/s/gf22ssjt1a3dhjm/swift-4.1.3-RPi23-Ubuntu1604.tgz?dl=0

**Comment by Bouke** [comment]
Indeed it does!
