### ISSUE TITLE
Drop-in replacement for Apple's NetService?

### ISSUE THREAD

**Issue by robreuss** [Bouke/NetService#15]
Super-excited to find your project - it is exactly what I need.  I'm adding support for Linux to an existing iOS project that already utilizes Apple's NetService framework.  I was wondering if your framework utilizes the same interface as Apple's so that I could just drop it into my project.  It looks very similar but it would be really helpful to know any divergence in advance.

**Comment by Bouke** [comment]
Hi Rob, I'm glad that this library might prove useful to you! The goal of this library is to be a drop-in replacement to Apple's framework. Currently publishing a service is mostly implemented, but browsing for services is not ([see "not implemented" markings][0]). The API is differing a little bit, as some classes used by Apple cannot be instantiated by this library. You can use compile-time if statements to work around this, see [this example](https://github.com/Bouke/HAP/blob/82c4f0ab1a341bf854319e957c265440fbce4452/Sources/HAP/Server/Server.swift#L170-L189).

This package implements mDNS itself. I'm currently in the process of trying to use the Avahi backend for this instead. I'm not sure if/when/how this new backend will be available, but will mention this in either release notes / readme when appropriate.

Let me know if you run into any issues.

[0]: https://github.com/Bouke/NetService/blob/master/Sources/NetService/NetService.swift

**Comment by robreuss** [comment]
Thanks for responding so quickly!  

I'm creating connections over the network between an iOS device and a Raspberry Pi, and so it's possible I'll be able to run your service on the RPi, and Apple's browser on the iOS device and have them coordinate a connection.  Possible?  Is mDNS also used by Apple's browser?

No problem to use compile time statements/stubs to work around - I already do that a lot because my framework runs on both and involves unsupported Apple frameworks unneeded on the Linux side.

**Comment by Bouke** [comment]
Well you're in luck, the Raspberry Pi is also my target architecture. It makes things, well let's say, more interesting. I'm running Raspbian Stretch. The Pi is 32 bits and most of development of Swift only takes 64 bits into account. As a result, there's segmentation faults left and right. Be sure to test often to prevent having to rewrite major parts of your application. As I have already many times.

mDNS is the technology powering NetService. It has many names Bonjour / ZeroConfig.

So with the current master branch you basically can do `NetService.publish` on the Linux side, but not `NetService.resolve`. Browsing is supported, but I think you'll have to setup connections yourself.

**Comment by robreuss** [comment]
Understood.  I'm currently running my Raspberry Pi on Mate 16.04.  I'll keep you posted as I move forward!  Thanks Bouke.
