### ISSUE TITLE
NetServiceBrowser: includesPeerToPeer

### ISSUE THREAD

**Issue by robreuss** [Bouke/NetService#16]
Is includesPeerToPeer (from Apple's version) not implemented in NetServiceBrowser?  I provide access to this property to developers using my framework, but I could easily compiler switch it out on Linux if it's a hassle for you to implement, or stub!

[https://developer.apple.com/documentation/foundation/netservice/1414086-includespeertopeer](url)

**Comment by Bouke** [comment]
Yeah no that is not available in this library, and I doubt if it ever will be. P2P seems to use WiFi-direct / Bonjour, whereas this library is limited to plain UDP mDNS.

In most situations I would just not offer a method/variable if it is not implemented, as that makes it clear to the consumer on compile time that things aren't available.

**Comment by robreuss** [comment]
No problem - I'll compile it out for now.  Thanks.
