### ISSUE TITLE
Unseen delegate protocols and stop() method

### ISSUE THREAD

**Issue by robreuss** [Bouke/NetService#17]
I have the module importing to my Raspberry Pi project no problem!  But for some reason it is not recognizing references to NetServiceDelegate, NetServiceBrowser and NetServiceBrowserDelegate.  

In perhaps a related issue, it does not see "stop()" on NetServiceBrowser, but I can see that method implemented in your source (even though I also see an issue from last year saying it requires implementation).

Importing "NetService" is the only module required, correct?  Thanks!

**Comment by robreuss** [comment]
I realized why the protocols were not being recognized.  I had a file full of NetService stubs around to enable execution under Linux.  I removed that file and although I still have some issues, that particular one is zapped!

Let me know about the "stop()" method.

**Comment by Bouke** [comment]
The `stop()` method should be available in 0.4.0 and above: https://github.com/Bouke/NetService/commit/a8311f8b7c7bcccf01f7aa1c87cb98d2dd98eea8.

**Comment by robreuss** [comment]
Super!  Thanks.
