### ISSUE TITLE
NetService conformation with protocol Hashable

### ISSUE THREAD

**Issue by robreuss** [Bouke/NetService#18]
I use references to NetService services as keys in a dictionary, so if it's possible to make it hashable that would be wonderful!  Thank you!

**Comment by Bouke** [comment]
You could add this through an extension as well I think?

**Comment by robreuss** [comment]
Great idea.  Thanks!

**Comment by robreuss** [comment]
This appears to have been resolved by upgrading Swift to 4.1.3.
