### ISSUE TITLE
getInputStream(_:outputStream:)

### ISSUE THREAD

**Issue by robreuss** [Bouke/NetService#19]
This seems to be a method available on Apple's NetService:
https://developer.apple.com/documentation/foundation/netservice/1418325-getinputstream

**Comment by Bouke** [comment]
It's not available in this library. There is a limitation imposed by Swift-Foundation that prevents us from creating arbitrary `Stream`s based off `CFStream`s. Other than that, I'd welcome a PR adding such functionality.

**Comment by robreuss** [comment]
I'm sorry but I'm a little rusty in my NetService knowledge.  Does stream creation exceed the service-discovery goals of Bonjour / Zeroconf / mDNS?  I assume based on what you have implemented, I'll be able to get an address and initiate my own connection on that basis?

**Comment by Bouke** [comment]
That's correct; after resolving a NetService, it provides you with [`addresses: [Data]`](https://developer.apple.com/documentation/foundation/netservice/1408528-addresses). However the API from Foundation is not so nice to use. This library provides [`addresses: [Socket.Address]`](https://github.com/Bouke/NetService/blob/33be23058c7d93bcdd2a05e1e0da32ade5213fc9/Sources/NetService/NetService.swift#L109) instead.

It might be nice to have something similar to `getInputStream(_:outputStream:)`, but as mentioned it can't return the same types as Apple's implementation.

**Comment by robreuss** [comment]
Cool.  Thanks.
