### ISSUE TITLE
Getting both IP address and port in netServiceDidResolveAddress

### ISSUE THREAD

**Issue by robreuss** [Bouke/NetService#20]
This is not directly related to your NetService framework but Apple's.  Do you have a recipe for extracting the port number from the `sender.addresses` property returned by netServiceDidResolveAddress?  This code is working to extract the address but I'm unable to modify it to get the port.  Insofar as it doesn't account for address types, it's probably insufficient even for the IP address?

`    func netServiceDidResolveAddress(_ sender: NetService) {
        
        var hostname = [CChar](repeating: 0, count: Int(NI_MAXHOST))
        guard let data = sender.addresses?.first else { return }
        do {
            try data.withUnsafeBytes { (pointer:UnsafePointer<sockaddr>) -> Void in
                guard getnameinfo(pointer, socklen_t(data.count), &hostname, socklen_t(hostname.count), nil, 0, NI_NUMERICHOST) == 0 else {
                    throw NSError(domain: "domain", code: 0, userInfo: ["error":"unable to get ip address"])
                }
            }
        } catch {
            logError("Could not get service IP address: \(error)")
            print(error)
            return
        }
        let address = String(cString:hostname)
        logDebug("\(sender.name)  IP:\(address)")
}`

**Comment by Bouke** [comment]
You're mostly there, but there's a few things to consider when working with the various `sockaddr` types, see also [here](https://stackoverflow.com/questions/16010622/reasoning-behind-c-sockets-sockaddr-and-sockaddr-storage).

Currently you're casting to `sockaddr`, which is what `getnameinfo` consumes. However to get the port number, you either need `sockaddr_in` or `sockaddr_in6`. See also [this snippet](https://github.com/Bouke/NetService/blob/33be23058c7d93bcdd2a05e1e0da32ade5213fc9/Sources/NetService/sockaddr_%2BExtensions.swift#L85-L110). In my dns-sd replica, you can see [similar code](https://github.com/Bouke/NetService/blob/ffe32596bcdd0e60661f83e0d9f4812f98bc35f9/Sources/dns-sd/Delegate.swift#L133-L167).

Usually you'd just get the port through the `NetService` instance however. The `addresses` can be used to setup a socket to the service.

**Comment by robreuss** [comment]
Super helpful.  I’m sure I can muddle through from here.  Thanks!
