### ISSUE TITLE
Not resolving (iOS client, Linux host)

### ISSUE THREAD

**Issue by robreuss** [Bouke/NetService#23]
Publishing service on Linux successfully, and iOS client is seeing the service and attempting to resolve, but nothing happens.  Any way I can do some logging with your NetService to help diagnose?  This occurs on both "dns_sd" and "master"

**Comment by robreuss** [comment]
I implemented the delegate for didNotResolve on the iOS (browsing) side and got this error after timeout:

`["NSNetServicesErrorCode": -72007, "NSNetServicesErrorDomain": 10]`

Again, services are seen by the browser as being on _local._, just won't resolve.  Thanks in advance!

**Comment by Bouke** [comment]
I cannot reproduce. I have published a service on Linux/RPi using the "dns_sd" branch (avahi). Using the iOS Simulator with the code below, it resolves just fine:

```
import UIKit

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate, NetServiceDelegate {

    var window: UIWindow?
    var service: NetService?

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {

        service = NetService(domain: "local", type: "_hap._tcp", name: "Thermostaat")
        service!.delegate = self
        service!.resolve(withTimeout: 5)

        return true
    }

    func netServiceWillResolve(_ sender: NetService) {
        NSLog("Will resolve \(sender)")
    }

    func netServiceDidResolveAddress(_ sender: NetService) {
        NSLog("Did resolve \(sender)")
    }

    func netService(_ sender: NetService, didNotResolve errorDict: [String : NSNumber]) {
        NSLog("Did not resolve \(sender), \(errorDict)")
    }
}
```

Outputs:
```
2018-12-10 23:17:57.177481+0100 NetServiceTest[44651:2111090] Will resolve <NSNetService 0x60000041aca0> local _hap._tcp Thermostaat -1
2018-12-10 23:17:57.217197+0100 NetServiceTest[44651:2111090] Did resolve <NSNetService 0x60000041aca0> local _hap._tcp Thermostaat 39031
```

**Comment by robreuss** [comment]
Still trying to figure this out.  Two questions.  Is the specification of the domain above as "local" rather than "local." (with a period suffix) a typo or should I be using "local"?  Apart from modifying the hostname to include the local domain (in my case, that makes the hostname "ubuntu.local"), are there any configuration changes on the linux side?  Thanks!

**Comment by robreuss** [comment]
BTW, I'm using "master" not "dns_sd" because the later does not compile - errors about "dns_sd.h" not being found.

**Comment by robreuss** [comment]
Another data point:

When I run "avahi-browse _vmc._tcp. --resolve --verbose" from my raspberry to my ubuntu VM (running bridged networking) I also get a failure to resolve, with this error information (which isn't very helpful):

```avahi-browse _vmc._tcp. --resolve --verbose
Server version: avahi 0.6.32-rc; Host name: ubuntu.local
E Ifce Prot Name                                          Type                 Domain
+  ens33 IPv4 Virtual Mobile Controller                     _vmc._tcp            local
Failed to resolve service 'Virtual Mobile Controller' of type '_vmc._tcp' in domain 'local': Timeout reached
: All for now
: Cache exhausted
```

In contrast, the command does resolve when going from Ubuntu to macOS (which is running Apple's NetService).

**Comment by robreuss** [comment]
iOS client is now resolving thanks to switching to "dns_sd" branch.
