### ISSUE TITLE
Example code allows port set to 0, but precondition in publishPhaseTwo requires port > 0

### ISSUE THREAD

**Issue by robreuss** [Bouke/NetService#24]

**Comment by Bouke** [comment]
The example code specifies `.listenForConnections` which makes `NetService` listen on a port assigned by the OS. That port is then used for the advertisements. You can't specify port 0 without `.listenForConnections`, as you've discovered.

**Comment by robreuss** [comment]
Thanks.  I backed away from that configuration because when I try to use BlueSocket to listen on the assigned port, it gives me an "Address already in use" error.  I'm following up with the author of that package.
