### ISSUE TITLE
Disabled didAcceptConnectionWith in the "dns_sd" branch

### ISSUE THREAD

**Issue by robreuss** [Bouke/NetService#27]
Looks like the delegate "didAcceptConnectionWith" has been disabled in the "dns_sd" branch.  Is that a temporary or permanent change?

**Comment by Bouke** [comment]
I’m not sure if I’ll be implementing this. I cannot create `InputStream` and `OutputStream`, so I would have to use other socket library, or implement sockets myself with all the platform differences. Ideally Swift-Foundation allows me to create those types.

**Comment by robreuss** [comment]
I understand.  I bet I can work with whatever you do.

I originally planned to use NetService (yours and Apple's) strictly to provide a browsable service, and then hand off to BlueSocket TCP and UDP servers.  However, I ran into a problem where Apple's NetService would seem to block the TCP server from starting up on the port it assigned.  BlueSocket would give an address already in use error.  It seems as if so long as Apple's NetService is publicizing a service for a given port, it reserves control of that port, presumably because it wants to spawn streams off of it.

**Comment by Bouke** [comment]
If you want to control the sockets yourself, you shouldn’t pass the `listenForConnections` option. Then it is up to you to setup the sockets and listen for connections.

**Comment by robreuss** [comment]
I think without the "listenForConnections" option, passing a port value of 0 doesn't result in a dynamically allocated port, which is what I'm looking for.

**Comment by robreuss** [comment]
I've got an idea to get around the problem of NetService occupying the assigned port when passed a port of 0 and "listenForConnections".  I could initially start the service that way, and then when I receive the didPublish delegate call with the assigned port, I would do this:  

```
netService?.stop()
...launch TCP server on assigned port...
netService = NetService(domain: ElementalController.serviceDomain, type: ElementalController.serviceType(serviceName: serviceName, proto: .tcp), name: "Test republish", port: Int32(sender.port))
netService?.delegate = self
netService?.publish() 

```
By republishing the service without the "listenForConnections" and with the assigned port specified, my service would be published while NetService would leave that port alone instead of setting up streams.

Would that work with your library as well?  Do you think it's too much of a hack in general?

**Comment by Bouke** [comment]
No it's a shortcoming currently that the parameters aren't checked correctly. Either you pass in a specific port, or you set "listenForConnections".

The OS will provide you with a dynamic port if you open a socket and don't bind it to a specific port. NetService doesn't do anything magical here, if you ask it to open a port on 0, it'll be assigned a port by the OS. That port will be used for the bonjour advertisements.

So the current master branch does support listenForConnections. In contrast to Apple's implementation it'll send a (BlueSocket) Socket when a client connects. The dns_sd branch doesn't support listenForConnections, and should probably reject that option and also require the port > 0. Using the dns_sd branch, you'd currently have to setup your own listening socket prior to the bonjour broadcast. You could use BlueSocket for example. Once you have the listening socket up, you'll know the port and you can use NetService to broadcast that port.

**Comment by robreuss** [comment]
Sorry if I wasn't clear - the solution I outlined above was intended to overcome the behavior of Apple's NetService, not yours.  

BlueSocket documentation doesn't discuss the option of setting port to zero (0) as a means of getting an OS-assigned available port but I found [this issue](https://github.com/IBM-Swift/BlueSocket/issues/22) which suggests that it's there.

It's a good idea to start the TCP server first if I can convince BlueSocket to assign a port for me, and then advertise the service on that port.  I'll give that a spin - it'll solve problems.  Thank you!

**Comment by robreuss** [comment]
Looks like your suggestion is going to work!  

1. Publish BlueSocket TCP server with a port of 0.
2. BlueSocket will dynamically assign a port (I just proved this).
3. Advertise my service on that assigned port (I haven't completely proved NetService won't complain  but it seems to be working!)

Can you confirm that this should work on the dns_sd branch?  

Thanks!

**Comment by robreuss** [comment]
I implemented the approach above and everything is working now, including resolution on Linux!  Can't wait to deploy this on my RPi and start controlling things!  You've been a big help.  Thanks.

**Comment by robreuss** [comment]
It worked "out of the box" on Ubuntu Mate 16.04 running on my Raspberry!  

I built a little robot vehicle recently so the next goal will be to control the vehicle with my iPhone using Core Motion.
