### ISSUE TITLE
Packaging as a library with a branch dependency

### ISSUE THREAD

**Issue by robreuss** [Bouke/NetService#28]
I was able to get my library running as an executable on Ubuntu 16.04 referencing the "dns_sd" branch as a dependency.  However, when I switched to packaging as a library for another executable to use my library as a dependency, the Package Manager complained about using a branch dependency within a library.  It doesn't like using revision id numbers either.

I tried forking your NetService and merging "dns_sd" into master, but although things build, there's no service activity when running.  Do you have any suggestions on how I might utilize the"dns_sd" branch in a library, because that is working great?

I realize this question is a bit off the track of NetService itself but I was hoping you might be able to help.

**Comment by Bouke** [comment]
Should be possible, e.g. https://github.com/Bouke/HAP/blob/swift-nio-http/Package.swift where I do the same. The syntax keeps changing with every Swift releas, which can be annoying.

**Comment by robreuss** [comment]
I managed to get it working, thanks.  SPM can be a bit unpredictable in terms of reflecting changes to dependencies in the manifest.
