### ISSUE TITLE
NetService publishing error -65540

### ISSUE THREAD

**Issue by robreuss** [Bouke/NetService#29]
I'm having a bit trouble running my service on Ubuntu 16.05 in a VM and Ubuntu Mate on Raspberry.  It was working a couple of weeks ago.  It runs okay on MacOS and iOS.  No changes on the Linux side of the equation, and minimal changes (but some) to the subsystem in my framework, so that's probably the cause.  These Apple NetService error codes are very opaque.

The _didNotPublish_ delegate call is called and gives the following error code:

``` ["NSNetServicesErrorCode": -65540, "NSNetServicesErrorDomain": 10]```

Are you familiar with that one?  As a reminder, I'm using the _dns_sd_ branch.

**Comment by robreuss** [comment]
I finally found the reference for the -65540 error - it's _kDNSServiceErr_BadParam_.  One case you get that is if you're specified no auto-rename and there's a name collision.  I've tried fresh names and confirmed I don't have conflicting services running, but no go.  Also, I don't think if that were the issue I wouldn't also see it on MacOS and iOS.  

One recent change has been implementing Pi-Hole on my local network.  I've disabled it (turned off the RPi Zero it's running on) but to no avail.  If that were it, it would need to relate to some peculiarity of how Linux handles LAN DNS, again since it works for MacOS.

**Comment by Bouke** [comment]
With installing PiHole my guess is that the IP of the machine has also changed. I think the machine sees the old IP address as the conflicting one. The old one might be cached by other systems that respond in its place. You probably need to reboot all those machines to clear the cache. Also, it’s safer to use auto renaming, for situations like this.

**Comment by robreuss** [comment]
I figured it out.  I had changed my test code to pass an empty string as the service "name" based on how Apple's implementation allows that and will use the machine name instead:
https://developer.apple.com/documentation/foundation/netservice/1413364-init

If you modify your example code to pass an empty name you'll see the -65540 bad parameter error.  

I can work around this difference.  Do you know how I can get the linux host name from Swift?
